#!/usr/bin/with-contenv bash

# check for preferences file, make lock file if not found and exit out
if [ ! -e "${CONFIG}/Library/Application Support/Plex Media Server/Preferences.xml" ]; then
mkdir -p "${CONFIG}/Library"
touch "${CONFIG}/Library/linuxserver-chown.lock"
chown abc:abc \
	"${CONFIG}/Library"
chown abc:abc \
	"${CONFIG}/Library/linuxserver-chown.lock"
exit 0
fi

if [ ! -f "${CONFIG}/Library/linuxserver-chown.lock" ]; then
echo "Possible migration from existing version detected, please be patient while we chown existing files"
echo "This could take some time"
chown abc:abc -R \
	"${CONFIG}/Library"
touch "${CONFIG}/Library/linuxserver-chown.lock"
chown abc:abc \
	"${CONFIG}/Library/linuxserver-chown.lock"
echo "chown operation completed"
fi
